# Generated by Django 6.1.1 on 2026-09-24 23:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('lgpd_consent', models.BooleanField(default=False, verbose_name='Consentimento LGPD Concedido')),
                ('lgpd_consent_version', models.CharField(default='1.0', max_length=20, verbose_name='Versão do Termo Aceito')),
                ('lgpd_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Consentimento')),
                ('lgpd_consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Consentimento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login efetuado com sucesso'), ('LOGIN_FAILED', 'Falha na autenticação (senha incorreta/e-mail inexistente)'), ('LOGOUT', 'Logout efetuado'), ('USER_REGISTER', 'Novo estudante cadastrado'), ('CONSENT_ACCEPTED', 'Termo de Consentimento LGPD aceito'), ('DATA_EXPORT', 'Exportação de dados pessoais solicitada (Art. 18 LGPD)'), ('ACCOUNT_DELETED', 'Solicitação de exclusão/anonimização de conta')], max_length=30, verbose_name='Ação Realizada')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navegador / Dispositivo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora (UTC)')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes Adicionais')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
