# Generated by Django 6.1.1 on 2026-09-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_action_twofactorcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twofactorcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login efetuado com sucesso'), ('LOGIN_FAILED', 'Falha na autenticação (senha incorreta/e-mail inexistente)'), ('2FA_SENT', 'Código de autenticação 2FA enviado por e-mail'), ('2FA_VERIFIED', 'Autenticação 2FA verificada com sucesso'), ('2FA_FAILED', 'Código 2FA incorreto ou expirado'), ('PASSWORD_RESET_REQUEST', 'Solicitação de recuperação de senha por e-mail'), ('PASSWORD_RESET_SUCCESS', 'Senha redefinida com sucesso'), ('LOGOUT', 'Logout efetuado'), ('USER_REGISTER', 'Novo estudante cadastrado'), ('CONSENT_ACCEPTED', 'Termo de Consentimento LGPD aceito'), ('DATA_EXPORT', 'Exportação de dados pessoais solicitada (Art. 18 LGPD)'), ('ACCOUNT_DELETED', 'Solicitação de exclusão/anonimização de conta')], max_length=30, verbose_name='Ação Realizada'),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, verbose_name='Hash SHA-256 do Código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('is_used', models.BooleanField(default=False, verbose_name='Código Utilizado?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Redefinição de Senha',
                'verbose_name_plural': 'Códigos de Redefinição de Senha',
                'ordering': ['-created_at'],
            },
        ),
    ]
